import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'
import styled from 'styled-components'
import Marquee from "react-fast-marquee"

const variants = {
  hidden: { opacity: 0 },
  enter: { opacity: 1 },
  exit: { opacity: 0 },
}

const Main = styled(motion.main)`
  background: var(--primaryColor);
`;

const Bullet = styled.span`
  height: 12px;
  width: 12px;
  display: inline-block;
  background: red;
  border-radius: 100%;
`;

const StyledMarquee = styled(Marquee)`
  width: 50%;
  color: var(--accentColor);
  z-index: 0;
`;

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main
        variants={variants}
        initial="hidden"
        animate="enter"
        exit="exit"
        transition={{ type: 'linear'  }}
      >
        <StyledMarquee gradient={false}>
          <p>Graphic designer <Bullet /> UI Designer - UX Designer</p>
        </StyledMarquee>
        <h1>
          Nulla facilisi. Integer eu porttitor purus, ut viverra neque. Duis ac erat sed eros fermentum tincidunt quis quis erat. Nam pulvinar sapien varius, sagittis velit nec, ornare turpis. Maecenas pulvinar, odio a congue luctus, ipsum eros egestas eros, nec vulputate ante ipsum sollicitudin leo. Praesent et nisl ligula. Aliquam convallis sem pellentesque lorem porta, in tincidunt ipsum ultrices. Praesent sodales placerat dui in aliquet. Donec nec metus dui. Phasellus non risus eget purus efficitur pretium. Nunc malesuada lectus eros. Vivamus non molestie sem.

        Vestibulum eu imperdiet purus. Quisque tristique nisl vitae urna luctus, sit amet semper metus viverra. Quisque interdum leo posuere tortor eleifend, nec aliquet tortor fermentum. Etiam facilisis nulla eget lectus cursus, et laoreet sapien pellentesque. Proin a orci congue odio mollis varius sed finibus lectus. Donec ut diam rhoncus, rutrum nisi at, eleifend augue. Pellentesque gravida ante ut nibh rhoncus pellentesque. Morbi eu libero malesuada, volutpat sem ut, pellentesque justo. Donec iaculis, leo ut placerat convallis, sem metus egestas odio, sit amet ullamcorper orci nunc sit amet est. Proin iaculis et neque a dictum. Aliquam et sem sed elit pulvinar fringilla at at lacus. Nullam tortor odio, bibendum at faucibus suscipit, luctus sed tellus. Morbi id nulla quis sapien auctor aliquam. Vivamus ut lorem molestie, cursus purus at, consectetur ligula.

        Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam tempor ultrices est, vitae ullamcorper metus. Maecenas in accumsan libero, nec feugiat erat. Fusce lacinia venenatis nunc, at placerat elit congue ut. Suspendisse ullamcorper nibh id vestibulum interdum. Ut interdum dapibus eros, vitae ultrices urna imperdiet nec. Praesent nisi orci, facilisis a lobortis a, porta et mauris. Donec ut nisi vitae turpis iaculis aliquam eget fringilla ligula. Donec aliquet gravida nisl, eget tempus quam sodales et. Donec sit amet pellentesque dui, vitae facilisis sapien. Donec auctor turpis non arcu pharetra porttitor. Etiam suscipit sem tellus, in scelerisque nibh tempus at. Sed pharetra elit lectus, sit amet eleifend purus rhoncus quis.

        Nunc tempus augue mauris, sit amet tincidunt odio mollis ac. Ut sodales mi lorem, convallis ullamcorper tellus elementum in. Pellentesque vel nibh iaculis, mattis purus eget, pharetra nisl. Etiam blandit tempor interdum. Etiam urna mauris, ultrices ut est quis, congue malesuada risus. Proin vitae facilisis quam, et pulvinar quam. Interdum et malesuada fames ac ante ipsum primis in faucibus.

        Sed posuere, ante et dictum pellentesque, tortor dui bibendum ligula, in consectetur dui erat ac nulla. Proin eu gravida lacus, ornare scelerisque metus. Sed lorem eros, ultrices eu egestas eu, bibendum non risus. Suspendisse sed est vel augue mattis aliquam. Nunc condimentum, sapien at iaculis aliquam, sapien elit pretium felis, ut fringilla ligula nulla et metus. Morbi magna urna, fermentum ac facilisis quis, lacinia sagittis eros. Quisque feugiat nisl non euismod hendrerit. Maecenas et dolor sagittis quam gravida pharetra. Cras viverra varius erat et ultrices.
          Nulla facilisi. Integer eu porttitor purus, ut viverra neque. Duis ac erat sed eros fermentum tincidunt quis quis erat. Nam pulvinar sapien varius, sagittis velit nec, ornare turpis. Maecenas pulvinar, odio a congue luctus, ipsum eros egestas eros, nec vulputate ante ipsum sollicitudin leo. Praesent et nisl ligula. Aliquam convallis sem pellentesque lorem porta, in tincidunt ipsum ultrices. Praesent sodales placerat dui in aliquet. Donec nec metus dui. Phasellus non risus eget purus efficitur pretium. Nunc malesuada lectus eros. Vivamus non molestie sem.

        Vestibulum eu imperdiet purus. Quisque tristique nisl vitae urna luctus, sit amet semper metus viverra. Quisque interdum leo posuere tortor eleifend, nec aliquet tortor fermentum. Etiam facilisis nulla eget lectus cursus, et laoreet sapien pellentesque. Proin a orci congue odio mollis varius sed finibus lectus. Donec ut diam rhoncus, rutrum nisi at, eleifend augue. Pellentesque gravida ante ut nibh rhoncus pellentesque. Morbi eu libero malesuada, volutpat sem ut, pellentesque justo. Donec iaculis, leo ut placerat convallis, sem metus egestas odio, sit amet ullamcorper orci nunc sit amet est. Proin iaculis et neque a dictum. Aliquam et sem sed elit pulvinar fringilla at at lacus. Nullam tortor odio, bibendum at faucibus suscipit, luctus sed tellus. Morbi id nulla quis sapien auctor aliquam. Vivamus ut lorem molestie, cursus purus at, consectetur ligula.

    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam tempor ultrices est, vitae ullamcorper metus. Maecenas in accumsan libero, nec feugiat erat. Fusce lacinia venenatis nunc, at placerat elit congue ut. Suspendisse ullamcorper nibh id vestibulum interdum. Ut interdum dapibus eros, vitae ultrices urna imperdiet nec. Praesent nisi orci, facilisis a lobortis a, porta et mauris. Donec ut nisi vitae turpis iaculis aliquam eget fringilla ligula. Donec aliquet gravida nisl, eget tempus quam sodales et. Donec sit amet pellentesque dui, vitae facilisis sapien. Donec auctor turpis non arcu pharetra porttitor. Etiam suscipit sem tellus, in scelerisque nibh tempus at. Sed pharetra elit lectus, sit amet eleifend purus rhoncus quis.

    Nunc tempus augue mauris, sit amet tincidunt odio mollis ac. Ut sodales mi lorem, convallis ullamcorper tellus elementum in. Pellentesque vel nibh iaculis, mattis purus eget, pharetra nisl. Etiam blandit tempor interdum. Etiam urna mauris, ultrices ut est quis, congue malesuada risus. Proin vitae facilisis quam, et pulvinar quam. Interdum et malesuada fames ac ante ipsum primis in faucibus.

    Sed posuere, ante et dictum pellentesque, tortor dui bibendum ligula, in consectetur dui erat ac nulla. Proin eu gravida lacus, ornare scelerisque metus. Sed lorem eros, ultrices eu egestas eu, bibendum non risus. Suspendisse sed est vel augue mattis aliquam. Nunc condimentum, sapien at iaculis aliquam, sapien elit pretium felis, ut fringilla ligula nulla et metus. Morbi magna urna, fermentum ac facilisis quis, lacinia sagittis eros. Quisque feugiat nisl non euismod hendrerit. Maecenas et dolor sagittis quam gravida pharetra. Cras viverra varius erat et ultrices.
        </h1>
      </Main>
    </>
  )
}
