import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styled from 'styled-components'
import Marquee from "react-fast-marquee"

const Main = styled.main`
  padding-top: 15rem;
`;

const Bullet = styled.span`
  height: 12px;
  width: 12px;
  display: inline-block;
  background: red;
  border-radius: 100%;
`;

const StyledMarquee = styled(Marquee)`
  width: 50%;
  color: var(--accentColor);
  z-index: 0;
`;

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <StyledMarquee gradient={false}>
          <p>Graphic designer <Bullet /> UI Designer - UX Designer</p>
        </StyledMarquee>
      </Main>
    </>
  )
}
